stages:
  - build
  - deploy

build:
  stage: build
  image: docker:dind
  # before_script:
  #   - docker login -u $AIC_DOCKERID -p $AIC_DOCKERPASS
  script:
    - docker build -t reg.aichallenge.ir/AIC22-BackEnd:latest .
    - docker push reg.aichallenge.ir/AIC22-BackEnd:latest
