stages:
  - build
  - deploy

build:
  stage: build
  image: docker:dind
  before_script:
    - docker login -u $AIC_DOCKERID -p $AIC_DOCKERPASS
  script:
    - docker build -t $AIC_DOCKERID/AIC22-BackEnd:latest .
    - docker push $AIC_DOCKERID/AIC22-BackEnd:latest
