stages:
  - build
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "add-production-deployment"'
      when: always
    - when: never

.stg-vars:
  variables:
    ENVIRONMENT: stg
    CORE_IMAGE: reg.aichallenge.ir/aic22-backend/core:stg
    STATICS_IMAGE: reg.aichallenge.ir/aic22-backend/static:stg
    CORE_CONTAINER_NAME: aic_backend_core_stg
    STATIC_CONTAINER_NAME: aic_backend_static_stg
  rules:
    - if: '$CI_COMMIT_BRANCH == "add-production-deployment"'
      when: always

.production-vars:
  variables:
    ENVIRONMENT: production
    CORE_IMAGE: reg.aichallenge.ir/aic22-backend/core:${CI_COMMIT_SHORT_SHA}
    STATICS_IMAGE: reg.aichallenge.ir/aic22-backend/static${CI_COMMIT_SHORT_SHA}
    CORE_CONTAINER_NAME: aic_backend_core_production
    STATIC_CONTAINER_NAME: aic_backend_static_production
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always

.build:
  stage: build
  image: reg.aichallenge.ir/docker:20.10.3-dind
  tags:
    - docker
  # before_script:
  #   - docker login -u $AIC_DOCKERID -p $AIC_DOCKERPASS
  script:
    - docker build -t ${CORE_IMAGE} --target build .
    - docker build -t ${STATICS_IMAGE} --target static .
    - docker push ${CORE_IMAGE}
    - docker push ${STATICS_IMAGE}

.deploy:
  stage: deploy
  before_script:
    - chmod -R 700 $SSH_PRIVATE_KEY
    - ssh -i $SSH_PRIVATE_KEY -o "StrictHostKeyChecking=no" ubuntu@188.121.111.163 -t "docker pull ${CORE_IMAGE}"
    - ssh -i $SSH_PRIVATE_KEY -o "StrictHostKeyChecking=no" ubuntu@188.121.111.163 -t "docker pull ${STATICS_IMAGE}"
    - ssh -i $SSH_PRIVATE_KEY -o "StrictHostKeyChecking=no" ubuntu@188.121.111.163 -t "docker rm -f ${CORE_CONTAINER_NAME} ${STATIC_CONTAINER_NAME}"
    - scp -i $SSH_PRIVATE_KEY -o "StrictHostKeyChecking=no" $ENV_FILE ubuntu@188.121.111.163:/tmp/
  script:
    - ssh -i $SSH_PRIVATE_KEY -o "StrictHostKeyChecking=no" ubuntu@188.121.111.163 -t "docker run --env-file /tmp/ENV_FILE -d -p 8181:8000 --name=${CORE_CONTAINER_NAME} ${CORE_IMAGE} && docker exec -i ${CORE_CONTAINER_NAME} python manage.py migrate"
    - ssh -i $SSH_PRIVATE_KEY -o "StrictHostKeyChecking=no" ubuntu@188.121.111.163 -t "docker run -d -p 81:80 --name=${STATIC_CONTAINER_NAME} ${STATICS_IMAGE}"


stg-build:
  extends:
    - .stg-vars
    - .build

production-build:
  extends:
    - .production-vars
    - .build

stg-deploy:
  extends:
    - .stg-vars
    - .deploy

production-deploy:
  extends:
    - .production-vars
    - .deploy