stages:
  - build
  - deploy

build:
  image: reg.aichallenge.ir/docker:20.10.3-dind
  stage: build
  tags:
    - docker
  before_script:
    - ping -c 5 reg.aichallenge.ir
  script:
    - docker build -t reg.aichallenge.ir/aic22-backend:latest .
    - docker push reg.aichallenge.ir/aic22-backend:latest

deploy:
  stage: deploy
  before_script:
    - chmod -R 700 $SSH_PRIVATE_KEY
    - ssh -i $SSH_PRIVATE_KEY -o "StrictHostKeyChecking=no" ubuntu@188.121.111.163 -t "docker pull reg.aichallenge.ir/aic22-backend:latest"
    - ssh -i $SSH_PRIVATE_KEY -o "StrictHostKeyChecking=no" ubuntu@188.121.111.163 -t "docker container rm -f aic_backend"
  script:
    - ssh -i $SSH_PRIVATE_KEY -o "StrictHostKeyChecking=no" ubuntu@188.121.111.163 -t "docker run -d --name=aic_backend reg.aichallenge.ir/aic22-backend:latest"
